apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-shanviapp
  labels:
    app: shanviapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: shanviapp
  template:
    metadata:
      labels:
        app: shanviapp
    spec:
      containers:
      - name: container-shanviapp
        image: srikanta1219/shanvi:13
        ports:
        - containerPort: 80