apiVersion: v1
kind: ResourceQuota
metadata:
     name: compute-quota
     namespace: dev
spec:
  hard:
    pods: "5"
    requests.cpu: "1"
    requests.memory: 512m
    limits.cpu: "2"
    limits.memory: 1Gi