apiVersion: v1
kind: ReplicationController
metadata:
  name: rahulapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
          app: myapp
          type: front-end
    spec:
      containers:
        - name: nginx-app-cont
          image: redis
  replicas: 5
