apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs-front
  labels:
    app: myapp
    name: front-end
spec:
  template:
    metadata:
      name: myapp-pod-front
      labels:
          app: myapp
          type: front-end
    spec:
      containers:
        - name: nginx-app-cont
          image: nginx
  replicas: 6
  selector:
    matchLabels:
        type: front-end